name: Hello

on:
    push:
        branches:
            - main

jobs:
    my-job:
        runs-on: ubuntu-latest
        steps:
            - name: testing-hello
              run: ls
            - name: git
              uses: actions/checkout@v4
            - name: list
              run: ls
